from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_isaac_lab.p0_locomotion.create_env import create_train_and_eval_env
from rl_x.environments.custom_isaac_lab.p0_locomotion.default_config import get_config
from rl_x.environments.custom_isaac_lab.p0_locomotion.general_properties import GeneralProperties


CUSTOM_ISAAC_LAB_P0_LOCOMOTION = extract_environment_name_from_file(__file__)
register_environment(CUSTOM_ISAAC_LAB_P0_LOCOMOTION, get_config, create_train_and_eval_env, GeneralProperties)
